### PR TITLE
CHERI: Fix capability provenance in WordLock.

### PR DESCRIPTION
**Pull request by jacobbramley**
Metadata is inherited from the left hand side of `|=`, so each of these sequences combined the old metadata with the new address.

None of the flag bits actually need to be inherited from the old pointers — they are either known (and checked) or overridden — so this patch also simplifies the sequences to make them easier to audit.

### CODE REVIEW

**Comment by jacobbramley** [comment]
bors try

**Comment by ltratt** [comment]
bors try-

**Comment by ltratt** [comment]
bors ping

**Pull request merged**
